### PR TITLE
Upgrade tar to 6.1.11

### PR DESCRIPTION
**Pull request by KevinFCormier**
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
https://github.com/open-cluster-management/backlog/issues/16617

### CODE REVIEW

**Comment by Randy424** [comment]
There are a few upgrade happening along side tar, I think an unintended upgrade is causing the test failure. Yaml object is referencing deprecated functions for example. 🤔
``` Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.```

**Comment by KevinFCormier** [comment]
Thanks, @Randy424. We had an undeclared direct dependency on js-yaml, so we were just using whatever was provided by our sub-dependencies. Fixed now.

**Pull request merged**
