### PR TITLE
Remove `strongswan` as a cable driver option

### PR DESCRIPTION
**Pull request by Jaanki**
....as Submariner no longer supports it.

Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
Please split this up into two separate PRs — one for the strongSwan removal, the other for the documentation link.

**Comment by Jaanki** [comment]
> Please split this up into two separate PRs — one for the strongSwan removal, the other for the documentation link.

Done

/remove-hold

**Pull request merged**
