### PR TITLE
Update Discovery RBAC States

### PR DESCRIPTION
**Pull request by zkayyali812**
https://github.com/open-cluster-management/backlog/issues/12827

image

RBAC check on namespace selection - 
image

### CODE REVIEW

**Review by jamestalton — APPROVED** [review]
lgtm

**Review by nathanweatherly — APPROVED** [review]

**Review by swopebe — APPROVED** [review]
thanks for pulling me in!

**Review by jamestalton — APPROVED** [review]
lgtm

**Pull request merged**
