### PR TITLE
Modal cluster sets empty table fix

### PR DESCRIPTION
**Pull request by Randy424**
Prop to stop Table render after submit and during submission in-progress.
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>
regarding: https://github.com/open-cluster-management/backlog/issues/12997

https://user-images.githubusercontent.com/21374229/132753849-6d3d124d-edf2-4a31-9c47-a4bfd5ac9f4c.mov

### CODE REVIEW

**Comment by KevinFCormier** [comment]
/hold

Were we going to bring back the delay so that the user sees the progress bar?
https://github.com/open-cluster-management/console/pull/674/files#diff-694c0a04c5c4105651ef6949df025774ed3413248620c5e3eedcc0a57a01ceaf

**Comment by Randy424** [comment]
@KevinFCormier Thanks, forgot to pull that over to the new branch I made.

**Pull request merged**
