### PR TITLE
Api route for Ansible Job Templates (feature)

### PR DESCRIPTION
**Pull request by Randy424**
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>

My first iteration on the API route for our job template route.
NOTE: This is a PR from my fork to @chenz4027 feature branch, not to main.

Using this code you can demo the feature:
Screen Shot 2021-07-27 at 3 23 30 PM

Output: 
Screen Shot 2021-07-27 at 3 24 43 PM

### CODE REVIEW

**Comment by chenz4027** [comment]
Great work! It only works for single host & token I assume?

**Comment by Randy424** [comment]
@chenz4027 correct

**Review by chenz4027 — APPROVED** [review]
lgtm

**Pull request merged**
