### PR TITLE
Add discovery telemetry annotations

### PR DESCRIPTION
**Pull request by zkayyali812**
Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>
https://github.com/open-cluster-management/backlog/issues/13106
https://github.com/open-cluster-management/backlog/issues/12830

### CODE REVIEW

**Review by jamestalton — APPROVED** [review]
lgtm

**Comment by joeg-pro** [comment]
FYI, we managed to get our wires crossed (probably my bad) and this PR is strictly related to backlog #13106 and not at all to backlog #12830.

**Pull request merged**
