### PR TITLE
Move "On Premises" into Providers section

### PR DESCRIPTION
**Pull request by mareklibra**
Depends on:
- [ ] https://github.com/open-cluster-management/temptifly/pull/136
- [x] https://github.com/openshift-assisted/assisted-ui-lib/pull/805

### CODE REVIEW

**Comment by mareklibra** [comment]
---

**Comment by matthewcarleton** [comment]
awesome, thank you

I can’t tell b/c of the pop-up but is there an (?) on the centrally managed heading?

with this content
Simplify cluster self-service with infrastructure environments, which enable you to manage hosts, create ready-to-use host groups, and quickly create clusters based on provided infrastructure. To use infrastructure environments, select On Premise.

can we also add some padding on the bottom of the card so there’s space below the TP label?

**Comment by mareklibra** [comment]
@matthewcarleton I had to add support for the tooltips but this is the result:

**Comment by rawagner** [comment]
@mareklibra since you're at it, can you please rename the card to `On-premise` ? It is the correct term

**Comment by mareklibra** [comment]
Closing, merged into #851

**Pull request closed without merging**
