### PR TITLE
Fix discovery page crash when secret missing label [2.4]

### PR DESCRIPTION
**Pull request by JakobGray**
Replace bang operator with optional chaining when checking for secret
provider type.

Issue: https://github.com/open-cluster-management/backlog/issues/18148

Signed-off-by: Jakob Gray <20209054+JakobGray@users.noreply.github.com>

### CODE REVIEW

**Comment by smithbw88** [comment]
Waiting on this to be merged before we can build 2.4.1 RC2.

**Comment by JakobGray** [comment]
@KevinFCormier Would you be able to approve this? It's the same change as https://github.com/open-cluster-management/console/pull/1013

**Pull request merged**
