### PR TITLE
Add application search-api queries

### PR DESCRIPTION
**Pull request by zlayne**
Signed-off-by: Zack Layne <zlayne@redhat.com>

Add infrastructure to auto-generate search-api Apollo query hooks.
Add the following application queries:
- applications
- subscriptions
- placementRules
- channels

### CODE REVIEW

**Comment by KevinFCormier** [comment]
My hope was that we would not continue to use search-api queries for the app lifecycle UI... but if we need to for the time being in order to get the app lifecycle UI, I would be OK with that.

@fxiang1 @chenz4027 what are your thoughts on this?

**Comment by chenz4027** [comment]
@KevinFCormier Hey Kevin, the reason I pinged Zack about the searchapi queries is because that advanced configuration table would need some fields that is provided by search, but not kube resource like app count and cluster count. If we could figure out a way to get those resources from kube instead of search, I'm good with that too

**Comment by fxiang1** [comment]
I think for getting the Argo applications on the managed clusters we would still need to use search for now. I know there's a proxy api in the works that would allow us to make direct kube call to managed clusters but not sure when that work will complete.

**Comment by fxiang1** [comment]
@chenz4027 I can help you with the app count and cluster count so you don't need to use search for the Advanced configuration table

**Comment by chenz4027** [comment]
@fxiang1 That would be great!

**Comment by zlayne** [comment]
Closing. We will use existing resource data instead of introducing new search queries.

**Pull request closed without merging**
